### ISSUE TITLE
[BUG] Cannot compile reducer

### ISSUE THREAD

**Issue by steveruizok** [orbitinghail/sqlsync#30]
**Describe the bug**
Cannot build the reducer (on MacOS).

**To Reproduce**
Follow the guide.
When running `cargo build --target wasm32-unknown-unknown --release`, get many errors such as `error[E0425]: cannot find function `v128_and` in this scope`. See full error log here: https://gist.github.com/steveruizok/7e2ef31bddaeaedfe738237eeb3d7048

**Comment by carlsverre** [comment]
It looks like you are using Rust nightly. I'll update the guide to specify that stable is required, as rust nightly is adding some new f128 features which are not supported in Wasm yet.

To fix this you can either change your default toolchain:
```
rustup default stable
```

Or use a specific toolchain for this build:
```
rustup run stable cargo build --target wasm32-unknown-unknown --release
```

Thanks for the report! Please let me know if this addresses the issue.
