### ISSUE TITLE
Update tsify to use siefkenj's fork

### ISSUE THREAD

**Issue by carlsverre** [orbitinghail/sqlsync#47]
Fork: https://github.com/siefkenj/tsify
Currently in next branch. Need to check and see what their plan is, but it looks like they are fixing most of the outstanding PRs

**Comment by carlsverre** [comment]
@siefkenj are you planning on merging everything down into the main branch once you're done preparing everything, or keeping the next branch? I'd be happy to test it out in this project (fairly extensive use of tsify) when you feel it's close to ready.

**Comment by siefkenj** [comment]
Thanks! I was planning on keeping everything on the `next` branch in case the original tsify project wakes back up...

**Comment by carlsverre** [comment]
@siefkenj just updated to use your branch and everything still works great. Thanks for doing that!
