### ISSUE TITLE
Do we miss a roadmap?

### ISSUE THREAD

**Issue by frederikhors** [orbitinghail/sqlsync#51]
This project is amazing! Really!

But I think we miss a roadmap.

Can we open an issue to pin to the top to collect ideas about the immediate and long future?

Thank you again for your work.

**Comment by carlsverre** [comment]
Hey @frederikhors thanks for your interest! Would you be ok with using discussions? You can find them here: https://github.com/orbitinghail/sqlsync/discussions/categories/ideas
