### ISSUE TITLE
Can use Sqlsync in executable file instead of web browser 

### ISSUE THREAD

**Issue by mrsavari** [orbitinghail/sqlsync#58]
**Can use Sqlsync in executable file instead of web browser .**
For offline first implementation?

**Comment by carlsverre** [comment]
Currently it's possible but not super easy. You can see all the code you would require to do this here: https://github.com/orbitinghail/sqlsync/blob/main/lib/sqlsync/examples/end-to-end-local-net.rs

But it's fairly manual at the moment.

What's your use case?
